#' @title RDRS spatial aggregator
#' @description
#' This function is designed for spatial aggregation of RDRS NetCDF files.
#' @param ncFile file path where NetCDF file is located
#' @param weightsFile (optional)  RDRS grid cells weights file path generated by \code{grids_weights_generator}. If missing, a uniform spatial aggregation is performed across the entire domain of the netcdf file.
#' @param OutFile The file path of the output ".csv" file to store the results
#' @return a "csv" object saved in the specified pile path in the \code{OutFile}, if missing the file will be save at the same location of the netcdf file
#' @export rdrs_nc_spatial_aggregator
#' @importFrom ncdf4 nc_open nc_close ncvar_get
#' @examples
#' dir.create("c:/rdrs")
#' setwd("c:/rdrs")
#' source("https://raw.githubusercontent.com/rarabzad/RDRS/main/rdrs_spatial_aggregator.R")
#' # download data
#' download.file("https://github.com/rarabzad/RDRS/raw/main/data.zip","data.zip")
#' unzip("data.zip")
#' ncFile<-list.files(pattern="*.nc")[1]
#' rdrs_spatial_aggregator(ncFile=ncFile)
#' @author Rezgar Arabzadeh, University of Waterloo, October 2023
rdrs_spatial_aggregator<-function(ncFile,
                                     weightsFile=NA,
                                     OutFile=NA)
{
  if(!file.exists(ncFile)) stop("provided nc file doesn't exist!")
  if(!grepl("\\.nc$", tolower(ncFile))) stop("for 'ncFile' wrong file format specified. Only '.nc' is accepted!")
  if(!is.na(weightsFile))
  {
    if(!file.exists(weightsFile)) stop("provided weight file doesn't exist!")
    if(!grepl("\\.txt$", tolower(weightsFile))) stop("for 'weightsFile' wrong file format specified. Only '.txt' is accepted!")
  }
  if(!is.na(OutFile)) if(!grepl("\\.csv$", tolower(OutFile))) stop("for 'OutFile' wrong file format specified. Only '.csv' is accepted!")
  if(is.na(OutFile)) OutFile<-file.path(dirname(ncFile),gsub(".nc","_aggregated.csv",basename(ncFile)))
  nc<-nc_open(ncFile)
  vars<-names(nc$var)[grep("RDRS",names(nc$var))]
  if(!is.na(weightsFile))
  {
    weights<-readLines(weightsFile,warn = F)
    weights<-weights[-grep("^\\s*#", weights)]
    weights<-weights[-grep("^\\s*:", weights)]
    weights<-read.table(text = weights, header = F)
    colnames(weights)<-c("spatial_unit","Cell_#","weight")
  }else{
    spatial_unit<-gsub(".nc","",basename(ncFile))
    Cell_id<-which(!is.na(ncvar_get(nc,vars[1])[,,1]))-1
    weight<-1/length(Cell_id)
    weights<-data.frame(spatial_unit,Cell_id,weight)
    colnames(weights)<-c("spatial_unit","Cell_#","weight")
  }
  spatial_unit<-unique(weights$spatial_unit)
  pattern <- "^(\\w+) since (\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2})$"
  start_time<-nc$dim$time$units
  match <- regexec(pattern, start_time)
  groups <- regmatches(start_time, match)
  time_step <- ifelse(groups[[1]][2] == "seconds","secs", groups[[1]][2])
  date_time <- groups[[1]][3]
  start_time <- as.POSIXct(date_time, format = "%Y-%m-%d %H:%M:%S")
  sequence_of_times <- start_time + as.difftime(nc$dim$time$vals, units = time_step)
  aggregated_data<-list()
  for(j in 1:length(vars))
  {
    cat(paste0("(",j,"/",length(vars),")", " #### Aggregating: ",vars[j]," ####\n"))
    mat<-matrix(NA,length(sequence_of_times),length(spatial_unit))
    var_data<-ncvar_get(nc,vars[j], collapse_degen = F)
    
    for(i in 1:length(spatial_unit))
    {
      w<-weights[weights$spatial_unit==spatial_unit[i],"weight"]
      id<-weights[weights$spatial_unit==spatial_unit[i],"Cell_#"]+1
      W<-var_data[,,1]
      W[]<-NA
      W[id]<-w
      W<-array(W, dim = c(dim(W), dim(var_data)[3]))
      mat[,i]<-apply(W*var_data,3,sum,na.rm=T)
    }
    mat<-as.data.frame(mat)
    rownames(mat)<-paste0(1:length(sequence_of_times),") ",as.character(sequence_of_times))
    colnames(mat)<-spatial_unit
    aggregated_data[[j]]<-mat
  }
  names(aggregated_data)<-vars
  aggregated_data<-do.call(cbind, aggregated_data)
  colnames(aggregated_data)<-apply(as.matrix(expand.grid(sprintf("(%s)",spatial_unit),vars)),1,paste, collapse = " ")
  write.csv(aggregated_data,OutFile)
  cat(paste("output file is saved at:",OutFile,"\n"))
}
